name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: make test
    
    - name: Build
      run: make build

    - name: Copy Files
      run: |
          mkdir artifacts
          cp lockbox artifacts/.
    
    - name: Archive
      uses: actions/upload-artifact@v2
      with:
          name: lockbox
          path: artifacts